services:
  blog-oauth2-db:
    image: "postgres:16.4-bullseye"
    container_name: "blog-oauth2-db"
    ports:
      - "5168:5432"
    volumes:
      - blog-oauth2-db-vol:/var/lib/postgrestsql/data
    networks:
      - blog-oauth2-net
    environment:
      - POSTGRES_PASSWORD=Seakngim123$
      - POSTGRES_USER=seakngim
      - POSTGRES_DB=blog_oauth2_db

volumes:
  blog-oauth2-db-vol:

networks:
  blog-oauth2-net:
